/** AI Responses — process markdown, render structured UI, execute actions. */
import { useState, useCallback, useEffect } from "react";
import { useQuery } from "@tanstack/react-query";
import {
  processAIMarkdown,
  executeAIAction,
  listAIResponses,
  type StructuredBlock,
} from "../api/client";
import AIResponseRenderer from "../components/AIResponseRenderer";

const SAMPLE_MARKDOWN = `## Weekly Report Summary

This week showed **positive** trends in patient engagement.

### Key Points
- Session attendance improved
- Documentation completeness at 94%

### Recommended Action
ACTION: open_queue_enterprise
LABEL: Review Enterprise Leads
CONFIDENCE: 0.91

---
*Generated by AI*`;

const ENTITY_ID = "report_demo_001";
const CONFIDENCE_THRESHOLD = 0.85;

export default function AIResponsesPage() {
  const [markdown, setMarkdown] = useState(SAMPLE_MARKDOWN);
  const [result, setResult] = useState<{
    id: string;
    structured_blocks: StructuredBlock[];
    confidence: number;
    needs_review: boolean;
  } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const { data: timelineItems = [], refetch: refetchTimeline } = useQuery({
    queryKey: ["ai-responses", ENTITY_ID],
    queryFn: () => listAIResponses(ENTITY_ID),
  });

  useEffect(() => {
    if (result) refetchTimeline();
  }, [result, refetchTimeline]);

  const handleProcess = useCallback(async () => {
    if (!markdown.trim()) return;
    setIsLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await processAIMarkdown({
        raw_markdown: markdown,
        entity_type: "weekly_report",
        entity_id: ENTITY_ID,
        model: "gpt-4",
        confidence: 0.91,
      });
      setResult({
        id: res.id,
        structured_blocks: res.structured_blocks,
        confidence: res.confidence,
        needs_review: res.needs_review,
      });
    } catch (e) {
      setError(e instanceof Error ? e.message : "Fehler");
    } finally {
      setIsLoading(false);
    }
  }, [markdown]);

  const handleActionClick = useCallback(
    async (block: StructuredBlock) => {
      if (!block.command || !block.label) return;
      try {
        await executeAIAction({
          command: block.command,
          label: block.label,
          confidence: block.confidence ?? 0,
          entity_type: "weekly_report",
          entity_id: ENTITY_ID,
        });
        alert(`Aktion "${block.label}" wurde ausgeführt (Command: ${block.command})`);
      } catch (e) {
        setError(e instanceof Error ? e.message : "Aktion fehlgeschlagen");
      }
    },
    []
  );

  return (
    <div className="flex flex-col gap-4 p-4">
      <h1 className="text-xl font-semibold text-gray-900 dark:text-white">
        KI-Antwort Rendering
      </h1>
      <p className="text-sm text-gray-600 dark:text-gray-400">
        Markdown eingeben oder Beispiel verwenden. Strukturierte Blöcke werden
        angezeigt; Aktionen werden protokolliert.
      </p>

      <div className="flex flex-col gap-2">
        <label
          htmlFor="markdown-input"
          className="text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Markdown
        </label>
        <textarea
          id="markdown-input"
          value={markdown}
          onChange={(e) => setMarkdown(e.target.value)}
          rows={12}
          className="min-h-[160px] w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-700 dark:text-white"
          placeholder="Markdown eingeben..."
        />
        <button
          type="button"
          onClick={handleProcess}
          disabled={isLoading || !markdown.trim()}
          className="min-h-touch min-w-touch w-full rounded-lg bg-primary-500 px-4 py-3 text-sm font-medium text-white hover:bg-primary-600 disabled:opacity-50 md:w-auto md:max-w-xs"
        >
          {isLoading ? "Wird verarbeitet…" : "Verarbeiten"}
        </button>
      </div>

      {error && (
        <div
          className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-800 dark:bg-red-900/30 dark:text-red-200"
          role="alert"
        >
          {error}
        </div>
      )}

      {result && (
        <section
          className="rounded-lg border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800"
          aria-label="Strukturierte Ausgabe"
        >
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
            Strukturierte Ausgabe
          </h2>
          <AIResponseRenderer
            blocks={result.structured_blocks}
            confidence={result.confidence}
            needsReview={result.needs_review}
            onActionClick={handleActionClick}
          />
        </section>
      )}

      {timelineItems.length > 0 && (
        <section
          className="rounded-lg border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800"
          aria-label="Timeline"
        >
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
            Timeline
          </h2>
          <ul className="mt-3 space-y-2">
            {timelineItems.map((item) => (
              <li
                key={item.id}
                className="flex items-start gap-3 rounded-lg border border-gray-200 p-3 dark:border-gray-600"
              >
                <span
                  className="flex min-h-touch min-w-touch shrink-0 items-center justify-center rounded bg-primary-100 text-primary-600 dark:bg-primary-900/50 dark:text-primary-400"
                  aria-hidden
                >
                  🤖
                </span>
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
                    <span>{item.model}</span>
                    <span>{(item.confidence * 100).toFixed(0)}%</span>
                    <span>v{item.version}</span>
                    <span>{new Date(item.created_at).toLocaleString("de-DE")}</span>
                  </div>
                  <button
                    type="button"
                    onClick={() =>
                      setExpandedId(expandedId === item.id ? null : item.id)
                    }
                    className="mt-1 text-left text-sm font-medium text-primary-600 hover:underline dark:text-primary-400"
                  >
                    {expandedId === item.id ? "Ausblenden" : "Vorschau anzeigen"}
                  </button>
                  {expandedId === item.id && (
                    <div className="mt-2 rounded border border-gray-200 p-2 dark:border-gray-600">
                      <AIResponseRenderer
                        blocks={item.structured_blocks}
                        confidence={item.confidence}
                        needsReview={item.confidence < CONFIDENCE_THRESHOLD}
                        onActionClick={handleActionClick}
                      />
                    </div>
                  )}
                </div>
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}
